# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dadosCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formDadosCliente(object):
    def setupUi(self, formDadosCliente):
        formDadosCliente.setObjectName("formDadosCliente")
        formDadosCliente.resize(454, 273)
        self.lb_nome = QtWidgets.QLabel(formDadosCliente)
        self.lb_nome.setGeometry(QtCore.QRect(20, 40, 61, 31))
        self.lb_nome.setObjectName("lb_nome")
        self.txt_nome = QtWidgets.QLineEdit(formDadosCliente)
        self.txt_nome.setGeometry(QtCore.QRect(100, 40, 331, 31))
        self.txt_nome.setText("")
        self.txt_nome.setObjectName("txt_nome")
        self.lb_telefone = QtWidgets.QLabel(formDadosCliente)
        self.lb_telefone.setGeometry(QtCore.QRect(20, 80, 71, 31))
        self.lb_telefone.setObjectName("lb_telefone")
        self.txt_telefone = QtWidgets.QLineEdit(formDadosCliente)
        self.txt_telefone.setGeometry(QtCore.QRect(100, 80, 331, 31))
        self.txt_telefone.setText("")
        self.txt_telefone.setObjectName("txt_telefone")
        self.lb_cidade = QtWidgets.QLabel(formDadosCliente)
        self.lb_cidade.setGeometry(QtCore.QRect(20, 120, 61, 31))
        self.lb_cidade.setObjectName("lb_cidade")
        self.txt_cidade = QtWidgets.QLineEdit(formDadosCliente)
        self.txt_cidade.setGeometry(QtCore.QRect(100, 120, 331, 31))
        self.txt_cidade.setText("")
        self.txt_cidade.setObjectName("txt_cidade")
        self.bt_cancelar = QtWidgets.QPushButton(formDadosCliente)
        self.bt_cancelar.setGeometry(QtCore.QRect(150, 180, 101, 51))
        self.bt_cancelar.setStyleSheet("image: url(:/icon_cancelar/icons/cancelar.png);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 0));")
        self.bt_cancelar.setText("")
        self.bt_cancelar.setObjectName("bt_cancelar")
        self.bt_cadastrar = QtWidgets.QPushButton(formDadosCliente)
        self.bt_cadastrar.setGeometry(QtCore.QRect(260, 180, 101, 51))
        self.bt_cadastrar.setStyleSheet("image: url(:/icon_cadastrar/icons/cadastrar.png);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 0));")
        self.bt_cadastrar.setText("")
        self.bt_cadastrar.setObjectName("bt_cadastrar")

        self.retranslateUi(formDadosCliente)
        QtCore.QMetaObject.connectSlotsByName(formDadosCliente)

    def retranslateUi(self, formDadosCliente):
        _translate = QtCore.QCoreApplication.translate
        formDadosCliente.setWindowTitle(_translate("formDadosCliente", "Form"))
        self.lb_nome.setText(_translate("formDadosCliente", "Nome:"))
        self.lb_telefone.setText(_translate("formDadosCliente", "Telefone:"))
        self.lb_cidade.setText(_translate("formDadosCliente", "Cidade:"))
        self.bt_cancelar.setToolTip(_translate("formDadosCliente", "<html><head/><body><p><img src=\":/icon_cliente/icons/cliente.png\"/></p></body></html>"))
        self.bt_cadastrar.setToolTip(_translate("formDadosCliente", "<html><head/><body><p><img src=\":/icon_cliente/icons/cliente.png\"/></p></body></html>"))
import icon_cadastrar_rc
import icon_cancelar_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formDadosCliente = QtWidgets.QWidget()
    ui = Ui_formDadosCliente()
    ui.setupUi(formDadosCliente)
    formDadosCliente.show()
    sys.exit(app.exec_())
