# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

### Import telas sistema ###
from cliente import Ui_formCliente

### Import de telas ###


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(927, 255)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_logoEmpresa = QtWidgets.QLabel(self.centralwidget)
        self.lb_logoEmpresa.setGeometry(QtCore.QRect(360, 110, 201, 91))
        self.lb_logoEmpresa.setStyleSheet("image: url(:/logo_empresa/icons/logo_empresa.png)")
        self.lb_logoEmpresa.setText("")
        self.lb_logoEmpresa.setObjectName("lb_logoEmpresa")
        self.bt_cliente = QtWidgets.QPushButton(self.centralwidget)
        self.bt_cliente.setGeometry(QtCore.QRect(10, 10, 101, 91))
        self.bt_cliente.setStyleSheet("image: url(:/icon_cliente/icons/cliente.png);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 0));")
        self.bt_cliente.setText("")
        self.bt_cliente.setObjectName("bt_cliente")
        self.bt_fornecedor = QtWidgets.QPushButton(self.centralwidget)
        self.bt_fornecedor.setGeometry(QtCore.QRect(110, 10, 101, 91))
        self.bt_fornecedor.setStyleSheet("image: url(:/icon_fornecedor/icons/fornecedor.png);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 0));\n"
"\n"
"")
        self.bt_fornecedor.setText("")
        self.bt_fornecedor.setObjectName("bt_fornecedor")
        self.bt_produtos = QtWidgets.QPushButton(self.centralwidget)
        self.bt_produtos.setGeometry(QtCore.QRect(210, 10, 101, 91))
        self.bt_produtos.setStyleSheet("image: url(:/icon_produtos/icons/produtos.png);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 0));")
        self.bt_produtos.setText("")
        self.bt_produtos.setObjectName("bt_produtos")
        self.bt_vendas = QtWidgets.QPushButton(self.centralwidget)
        self.bt_vendas.setGeometry(QtCore.QRect(310, 10, 101, 91))
        self.bt_vendas.setStyleSheet("image: url(:/icon_vendas/icons/venda.png);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 0));")
        self.bt_vendas.setText("")
        self.bt_vendas.setObjectName("bt_vendas")
        self.bt_pagar = QtWidgets.QPushButton(self.centralwidget)
        self.bt_pagar.setGeometry(QtCore.QRect(410, 10, 101, 91))
        self.bt_pagar.setStyleSheet("image: url(:/icon_pagar/icons/contasPagar.png);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 0));")
        self.bt_pagar.setText("")
        self.bt_pagar.setObjectName("bt_pagar")
        self.bt_bancos = QtWidgets.QPushButton(self.centralwidget)
        self.bt_bancos.setGeometry(QtCore.QRect(510, 10, 101, 91))
        self.bt_bancos.setStyleSheet("image: url(:/icon_bancos/icons/banco.png);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 0));")
        self.bt_bancos.setText("")
        self.bt_bancos.setObjectName("bt_bancos")
        self.bt_receber = QtWidgets.QPushButton(self.centralwidget)
        self.bt_receber.setGeometry(QtCore.QRect(610, 10, 101, 91))
        self.bt_receber.setStyleSheet("image: url(:/icon_receber/icons/receber.png);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 0));")
        self.bt_receber.setText("")
        self.bt_receber.setObjectName("bt_receber")
        self.bt_caixa = QtWidgets.QPushButton(self.centralwidget)
        self.bt_caixa.setGeometry(QtCore.QRect(710, 10, 101, 91))
        self.bt_caixa.setStyleSheet("image: url(:/icon_caixa/icons/caixa.png);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 0));")
        self.bt_caixa.setText("")
        self.bt_caixa.setObjectName("bt_caixa")
        self.bt_sair = QtWidgets.QPushButton(self.centralwidget)
        self.bt_sair.setGeometry(QtCore.QRect(810, 10, 101, 91))
        self.bt_sair.setStyleSheet("image: url(:/icon_sair/icons/sair.png);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 0));")
        self.bt_sair.setText("")
        self.bt_sair.setObjectName("bt_sair")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 927, 22))
        self.menubar.setObjectName("menubar")
        self.menuCadastros = QtWidgets.QMenu(self.menubar)
        self.menuCadastros.setObjectName("menuCadastros")
        self.menuOperacoes = QtWidgets.QMenu(self.menubar)
        self.menuOperacoes.setObjectName("menuOperacoes")
        self.menuSaida_de_produtos = QtWidgets.QMenu(self.menuOperacoes)
        self.menuSaida_de_produtos.setObjectName("menuSaida_de_produtos")
        self.menuEstoque = QtWidgets.QMenu(self.menuOperacoes)
        self.menuEstoque.setObjectName("menuEstoque")
        self.menuCompras = QtWidgets.QMenu(self.menuOperacoes)
        self.menuCompras.setObjectName("menuCompras")
        self.menuFinanceiro = QtWidgets.QMenu(self.menubar)
        self.menuFinanceiro.setObjectName("menuFinanceiro")
        self.menuConsultas = QtWidgets.QMenu(self.menubar)
        self.menuConsultas.setObjectName("menuConsultas")
        self.menuVendas = QtWidgets.QMenu(self.menuConsultas)
        self.menuVendas.setObjectName("menuVendas")
        self.menuConsumos = QtWidgets.QMenu(self.menuConsultas)
        self.menuConsumos.setObjectName("menuConsumos")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCliente = QtWidgets.QAction(MainWindow)
        self.actionCliente.setObjectName("actionCliente")
        self.actionFornecedor = QtWidgets.QAction(MainWindow)
        self.actionFornecedor.setObjectName("actionFornecedor")
        self.actionUsuario = QtWidgets.QAction(MainWindow)
        self.actionUsuario.setObjectName("actionUsuario")
        self.actionVenda = QtWidgets.QAction(MainWindow)
        self.actionVenda.setObjectName("actionVenda")
        self.actionConsumo_de_produtos = QtWidgets.QAction(MainWindow)
        self.actionConsumo_de_produtos.setObjectName("actionConsumo_de_produtos")
        self.actionSaldo = QtWidgets.QAction(MainWindow)
        self.actionSaldo.setObjectName("actionSaldo")
        self.actionCompras_2 = QtWidgets.QAction(MainWindow)
        self.actionCompras_2.setObjectName("actionCompras_2")
        self.actionPedido = QtWidgets.QAction(MainWindow)
        self.actionPedido.setObjectName("actionPedido")
        self.actionCancelar = QtWidgets.QAction(MainWindow)
        self.actionCancelar.setObjectName("actionCancelar")
        self.actionCaixa = QtWidgets.QAction(MainWindow)
        self.actionCaixa.setObjectName("actionCaixa")
        self.actionContas_Banco = QtWidgets.QAction(MainWindow)
        self.actionContas_Banco.setObjectName("actionContas_Banco")
        self.actionContas_pagar = QtWidgets.QAction(MainWindow)
        self.actionContas_pagar.setObjectName("actionContas_pagar")
        self.actionContas_receber = QtWidgets.QAction(MainWindow)
        self.actionContas_receber.setObjectName("actionContas_receber")
        self.actionContas_recebidas = QtWidgets.QAction(MainWindow)
        self.actionContas_recebidas.setObjectName("actionContas_recebidas")
        self.actionGeral = QtWidgets.QAction(MainWindow)
        self.actionGeral.setObjectName("actionGeral")
        self.actionResumido = QtWidgets.QAction(MainWindow)
        self.actionResumido.setObjectName("actionResumido")
        self.actionGeral_2 = QtWidgets.QAction(MainWindow)
        self.actionGeral_2.setObjectName("actionGeral_2")
        self.actionResumido_2 = QtWidgets.QAction(MainWindow)
        self.actionResumido_2.setObjectName("actionResumido_2")
        self.menuCadastros.addSeparator()
        self.menuCadastros.addAction(self.actionCliente)
        self.menuCadastros.addAction(self.actionFornecedor)
        self.menuCadastros.addAction(self.actionUsuario)
        self.menuSaida_de_produtos.addAction(self.actionVenda)
        self.menuSaida_de_produtos.addAction(self.actionConsumo_de_produtos)
        self.menuEstoque.addAction(self.actionSaldo)
        self.menuCompras.addAction(self.actionCompras_2)
        self.menuCompras.addAction(self.actionPedido)
        self.menuCompras.addAction(self.actionCancelar)
        self.menuOperacoes.addAction(self.menuSaida_de_produtos.menuAction())
        self.menuOperacoes.addSeparator()
        self.menuOperacoes.addAction(self.menuEstoque.menuAction())
        self.menuOperacoes.addAction(self.menuCompras.menuAction())
        self.menuFinanceiro.addAction(self.actionCaixa)
        self.menuFinanceiro.addAction(self.actionContas_Banco)
        self.menuFinanceiro.addAction(self.actionContas_pagar)
        self.menuFinanceiro.addAction(self.actionContas_receber)
        self.menuFinanceiro.addAction(self.actionContas_recebidas)
        self.menuVendas.addAction(self.actionGeral)
        self.menuVendas.addAction(self.actionResumido)
        self.menuConsumos.addAction(self.actionGeral_2)
        self.menuConsumos.addAction(self.actionResumido_2)
        self.menuConsultas.addAction(self.menuVendas.menuAction())
        self.menuConsultas.addAction(self.menuConsumos.menuAction())
        self.menubar.addAction(self.menuCadastros.menuAction())
        self.menubar.addAction(self.menuOperacoes.menuAction())
        self.menubar.addAction(self.menuFinanceiro.menuAction())
        self.menubar.addAction(self.menuConsultas.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_logoEmpresa.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_cliente.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/icon_cliente/icons/cliente.png\"/></p></body></html>"))
        self.bt_fornecedor.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/icon_cliente/icons/cliente.png\"/></p></body></html>"))
        self.bt_produtos.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/icon_cliente/icons/cliente.png\"/></p></body></html>"))
        self.bt_vendas.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/icon_cliente/icons/cliente.png\"/></p></body></html>"))
        self.bt_pagar.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/icon_cliente/icons/cliente.png\"/></p></body></html>"))
        self.bt_bancos.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/icon_cliente/icons/cliente.png\"/></p></body></html>"))
        self.bt_receber.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/icon_cliente/icons/cliente.png\"/></p></body></html>"))
        self.bt_caixa.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/icon_cliente/icons/cliente.png\"/></p></body></html>"))
        self.bt_sair.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/icon_cliente/icons/cliente.png\"/></p></body></html>"))
        self.menuCadastros.setTitle(_translate("MainWindow", "Cadastros"))
        self.menuOperacoes.setTitle(_translate("MainWindow", "Operacoes"))
        self.menuSaida_de_produtos.setTitle(_translate("MainWindow", "Saida de produtos"))
        self.menuEstoque.setTitle(_translate("MainWindow", "Estoque"))
        self.menuCompras.setTitle(_translate("MainWindow", "Compras"))
        self.menuFinanceiro.setTitle(_translate("MainWindow", "Financeiro"))
        self.menuConsultas.setTitle(_translate("MainWindow", "Consultas"))
        self.menuVendas.setTitle(_translate("MainWindow", "Vendas"))
        self.menuConsumos.setTitle(_translate("MainWindow", "Consumos"))
        self.actionCliente.setText(_translate("MainWindow", "Cliente"))
        self.actionFornecedor.setText(_translate("MainWindow", "Fornecedor"))
        self.actionUsuario.setText(_translate("MainWindow", "Usuarios"))
        self.actionVenda.setText(_translate("MainWindow", "Venda"))
        self.actionConsumo_de_produtos.setText(_translate("MainWindow", "Consumo de produtos"))
        self.actionSaldo.setText(_translate("MainWindow", "Saldo"))
        self.actionCompras_2.setText(_translate("MainWindow", "Comprar"))
        self.actionPedido.setText(_translate("MainWindow", "Pedido"))
        self.actionCancelar.setText(_translate("MainWindow", "Cancelar"))
        self.actionCaixa.setText(_translate("MainWindow", "Caixa"))
        self.actionContas_Banco.setText(_translate("MainWindow", "Contas Banco"))
        self.actionContas_pagar.setText(_translate("MainWindow", "Contas pagar"))
        self.actionContas_receber.setText(_translate("MainWindow", "Contas receber"))
        self.actionContas_recebidas.setText(_translate("MainWindow", "Contas recebidas"))
        self.actionGeral.setText(_translate("MainWindow", "Geral"))
        self.actionResumido.setText(_translate("MainWindow", "Resumido"))
        self.actionGeral_2.setText(_translate("MainWindow", "Geral"))
        self.actionResumido_2.setText(_translate("MainWindow", "Resumido"))


        ### BOTOES SISTEMA ###
        self.bt_sair.clicked.connect(self.sairSistema) # Fecha o sistema
        self.bt_cliente.clicked.connect(self.telaCliente) # botão Cliente abre telaCliente
        self.actionCliente.triggered.connect(self.telaCliente) # menuCliente abre telaCliente

    ### FUNCOES SISTEMA ###
    ## Fechar sistema ##
    def sairSistema(self):
        sys.exit()

    ## Abre telaCliente ##
    def telaCliente(self):
        self.formCliente = QtWidgets.QWidget()
        self.ui = Ui_formCliente()
        self.ui.setupUi(self.formCliente)
        self.formCliente.show()




### Imagens Sistema ###
import icon_bancos
import icon_caixa
import icon_cliente
import icon_fornecedor
import icon_pagar
import icon_produtos
import icon_receber
import icon_sair
import icon_vendas
import logo_empresa


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
